dist: focal

services:
  - docker

stages:
  - name: before_script
    if: branch = master

before_install:
  - docker-compose version

install:
  - git submodule update --init

before_script:
  - |
    if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
    fi

script:
  - docker-compose run --rm web hugo --minify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: true
  repo: devinus/devinus.github.io
  target-branch: master
  fqdn: devinus.io
  on:
    branch: master
